# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e27669d1bdae8fc3e976d42dc8e6b3af17ae884585dfce47e9dee93d807a924274d9da04be6f6fab5f899a4be8d7d832c70e5d6286a33675a73a79ac488dc9

test:
  secret_key_base: 6a40cc0e8c8f8ad1abac5a2e474b26238cb94b6a3cc7c2794b45c5be621f38824c5e9aa07b42beda2054c69c0036ae233e4c1a0a59552269b502229a688dd74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
